import fs from 'node:fs';
const required=['app/page.tsx','app/bepc/page.tsx','app/diagnostic/page.tsx','app/progres/page.tsx','app/dictionnaire/page.tsx','app/mathematiques/[lesson]/page.tsx','app/matiere/[subject]/page.tsx','app/matiere/[subject]/[lesson]/page.tsx','app/programme/page.tsx','app/programme/[subject]/page.tsx','app/programme/[subject]/[unit]/page.tsx','lib/learning.ts','lib/gamification.ts','lib/tutor.ts','lib/curriculum-3e.ts','lib/rich-lessons.ts','public/sw.js'];
const missing=required.filter(x=>!fs.existsSync(x));if(missing.length)throw new Error('Missing critical files: '+missing.join(', '));
const curriculum=fs.readFileSync('lib/curriculum-3e.ts','utf8');const subjects=['mathematiques','francais','physique-chimie','svt','histoire-geographie','anglais','edhc','espagnol','allemand','tice','eps','arts-plastiques','education-musicale'];for(const id of subjects)if(!curriculum.includes(`id:'${id}'`))throw new Error('Official subject missing: '+id);
const maths=fs.readFileSync('lib/maths-content.ts','utf8');const mathsCount=(maths.match(/\nL\('/g)||[]).length;if(mathsCount!==14)throw new Error('Expected 14 maths lessons, got '+mathsCount);
const rich=fs.readFileSync('lib/rich-lessons.ts','utf8');for(const token of ['why:','prerequisites:','simple:','detailed:','analogy:','workedSteps:','commonErrors:','memoryTip:','summary:','remediation:','tests:'])if(!rich.includes(token))throw new Error('Rich lesson contract missing '+token);
const richCount=(rich.match(/subject:'/g)||[]).length;if(richCount<5)throw new Error('Expected >=5 rich lessons, got '+richCount);
const mustContain=[['allemand',8],['tice',7],['arts-plastiques',9],['education-musicale',16]];for(const [id] of mustContain){if(!curriculum.includes(`id:'${id}'`))throw new Error('Coverage block missing '+id)}
if(!curriculum.includes('richKeys.has'))throw new Error('Enrichment status must be derived from rich lesson source');
console.log(`V1 integrity OK · 13 subjects · 14 maths lessons · ${richCount} rich lessons · canonical enrichment status`);
