import type {RichLesson} from './rich-lessons';
const mk=(subject:string,id:string,title:string,focus:string):RichLesson=>({id,subject,title,why:'Maîtriser cette unité permet de progresser dans le programme officiel de 3e et de réutiliser la compétence dans une situation concrète.',prerequisites:['Lire et comprendre une consigne','Mobiliser les acquis précédents'],simple:focus,detailed:focus+' Travaille d’abord la notion essentielle, observe un exemple, puis produis ou réalise toi-même la tâche sans regarder le modèle.',analogy:'La maîtrise vient par cycles courts : comprendre → essayer → corriger → recommencer plus tard.',workedSteps:['Identifier la tâche','Repérer les éléments essentiels','Observer ou préparer un modèle','Réaliser la tâche','Vérifier avec les critères'],commonErrors:[{error:'Rester spectateur et relire sans pratiquer.',fix:'Produis une réponse, un geste, une réalisation ou une phrase avant de vérifier.'}],memoryTip:'Comprendre → pratiquer → vérifier → revoir plus tard.',summary:[focus,'Pratiquer activement','S’auto-évaluer'],remediation:[{errorTag:id,message:'La compétence n’est pas encore stable.',action:'Reprendre un exemple plus simple puis refaire la tâche sans modèle.'}],tests:[{id:id+'-1',type:'short',prompt:'Explique ou réalise l’idée essentielle de cette unité avec un exemple.',answer:'réponse ou réalisation conforme aux critères du cours',explanation:'Vérifie que la notion centrale est comprise et appliquée.',difficulty:2,errorTag:id}]});
export const complementaryRichBatch:RichLesson[]=[
mk('espagnol','la-decouverte-du-monde-hispanique','La découverte du monde hispanique','Découvrir des repères culturels et linguistiques du monde hispanophone et savoir les présenter simplement.'),
mk('espagnol','la-presentation-des-civilites','La présentation des civilités','Saluer, se présenter et utiliser des formules de politesse adaptées en espagnol.'),
mk('espagnol','l-echange-d-information','L’échange d’information','Poser et comprendre des questions simples pour obtenir ou transmettre une information.'),
mk('espagnol','l-expression-d-opinion','L’expression d’opinion','Exprimer une opinion simple et la justifier avec des structures adaptées.'),
mk('espagnol','l-expression-des-gouts-et-des-preferences','L’expression des goûts et des préférences','Dire ce que l’on aime, préfère ou n’aime pas et comprendre les préférences d’autrui.'),
mk('espagnol','l-expression-des-sentiments','L’expression des sentiments','Exprimer des sentiments et comprendre des formulations simples liées aux émotions.'),
mk('espagnol','l-expression-de-l-ordre','L’expression de l’ordre','Comprendre et formuler des consignes ou ordres simples avec les formes étudiées.'),
mk('allemand','erster-kontakt','Erster Kontakt','Établir un premier contact et comprendre les expressions de base de présentation.'),
mk('allemand','begrussen','Begrüßen','Saluer et prendre congé avec des expressions adaptées.'),
mk('allemand','auf-dem-markt','Auf dem Markt','Utiliser le vocabulaire et les échanges utiles dans une situation de marché.'),
mk('allemand','eine-reise-nach-man','Eine Reise nach Man','Comprendre et produire des informations simples liées au voyage.'),
mk('allemand','mein-lieblingsfach','Mein Lieblingsfach','Parler de ses matières scolaires et exprimer une préférence.'),
mk('allemand','juliana','Juliana','Comprendre et exploiter les actes de communication associés à l’unité du manuel VORWÄRTS.'),
mk('allemand','ich-lade-dich-ein','Ich lade dich ein','Inviter, accepter ou refuser une invitation avec des formulations adaptées.'),
mk('allemand','mein-tageslauf','Mein Tageslauf','Décrire les principales étapes de sa journée et les situer dans le temps.'),
mk('tice','decouverte-d-un-reseau-informatique','Découverte d’un réseau informatique','Identifier les éléments et usages de base d’un réseau informatique.'),
mk('tice','utilisation-de-document-modele','Utilisation de document modèle','Utiliser un modèle pour produire un document cohérent et gagner du temps.'),
mk('tice','le-publipostage','Le publipostage','Comprendre le principe données + document modèle pour produire des documents personnalisés.'),
mk('tice','traitement-de-donnees-statistiques-avec-un-tableur','Traitement de données statistiques avec un tableur','Saisir, organiser et calculer des données dans un tableur.'),
mk('tice','traitement-graphique-des-donnees-avec-un-tableur','Traitement graphique des données avec un tableur','Choisir et produire une représentation graphique adaptée aux données.'),
mk('tice','decouverte-de-l-environnement-d-un-logiciel-de-presentation','Découverte d’un logiciel de présentation','Identifier l’environnement et les outils essentiels d’un logiciel de présentation.'),
mk('tice','conception-d-une-diapositive-dynamique-de-presentation','Conception d’une diapositive dynamique de présentation','Organiser texte, visuels et effets avec sobriété pour communiquer une idée.'),
mk('eps','courses-endurance-et-vitesse','Courses : endurance et vitesse','Comprendre les principes de gestion de l’effort, technique et sécurité adaptés aux courses étudiées.'),
mk('eps','gymnastique-au-sol','Gymnastique au sol','Construire et exécuter des éléments gymniques avec contrôle, enchaînement et sécurité.'),
mk('eps','activites-de-duel-lutte-africaine-judo','Activités de duel : lutte africaine / judo','Comprendre règles, sécurité, opposition et maîtrise de soi dans une activité de duel.'),
mk('eps','sauts-hauteur-longueur-triple-saut','Sauts : hauteur, longueur, triple saut','Relier course d’élan, impulsion, suspension et réception dans les sauts.'),
mk('eps','lancers-lancer-de-poids','Lancers : lancer de poids','Comprendre placement, poussée, coordination et sécurité du lancer.'),
mk('eps','sports-collectifs-football','Sports collectifs : football','Lire le jeu, coopérer, respecter les règles et choisir des actions utiles à l’équipe.'),
mk('arts-plastiques','bande-dessinee','Bande dessinée','Combiner image, cadrage, séquence et texte pour raconter visuellement.'),
mk('arts-plastiques','relation-texte-image','Relation texte/image','Comprendre comment texte et image se complètent, renforcent ou modifient le sens.'),
mk('arts-plastiques','depliant','Dépliant','Organiser informations, images et hiérarchie visuelle dans un support plié.'),
mk('arts-plastiques','beaute-corporelle-et-scarification','Beauté corporelle et scarification','Analyser des pratiques esthétiques et culturelles avec contexte et regard critique.'),
mk('arts-plastiques','equipements-socioculturels','Équipements socioculturels','Imaginer et représenter des solutions visuelles liées à des espaces socioculturels.'),
mk('arts-plastiques','gestion-et-protection-de-l-eau','Gestion et protection de l’eau','Utiliser la création visuelle pour sensibiliser à la gestion et à la protection de l’eau.'),
mk('arts-plastiques','artisanat-d-art-et-reduction-du-chomage','Artisanat d’art et réduction du chômage','Relier création, savoir-faire, production et opportunités économiques.'),
mk('arts-plastiques','art-negre-et-cubisme','Art nègre et cubisme','Observer des influences formelles de l’art africain dans l’histoire du cubisme sans réduire les œuvres à une imitation.'),
mk('arts-plastiques','ecriture-artistique-au-debut-du-20eme-siecle-et-naissance-de-l-art-abstrait','Écriture artistique au début du 20ème siècle et naissance de l’art abstrait','Comprendre le passage progressif de la représentation figurative vers des formes abstraites.'),
mk('education-musicale','l-abidjanaise-a-2-voix','L’Abidjanaise à 2 voix','Travailler écoute, justesse, rythme et coordination dans une interprétation à deux voix.'),
mk('education-musicale','la-tonalite-de-la-mineur-harmonique','La tonalité de La mineur harmonique','Identifier et pratiquer les éléments essentiels de la gamme de La mineur harmonique.'),
mk('education-musicale','la-musique-des-masques-we-dan-et-gouro','La musique des masques Wè, Dan et Gouro','Découvrir fonctions, contextes et caractéristiques musicales liées aux masques étudiés.'),
mk('education-musicale','les-mines-anti-personnel','Les mines anti-personnel','Exploiter une chanson ou activité musicale comme support de sensibilisation au thème étudié.'),
mk('education-musicale','le-demi-soupir-croche','Le demi-soupir croche','Lire et pratiquer la valeur rythmique étudiée dans des exercices simples.'),
mk('education-musicale','chanson-populaire-periode-1','Chanson populaire — période 1','Interpréter et analyser une chanson populaire selon les objectifs de la période.'),
mk('education-musicale','role-et-importance-de-l-impot','Rôle et importance de l’impôt','Mobiliser la pratique musicale comme support d’apprentissage et de sensibilisation au rôle de l’impôt.'),
mk('education-musicale','la-tonalite-de-re-mineur-harmonique','La tonalité de Ré mineur harmonique','Identifier et pratiquer les éléments essentiels de la gamme de Ré mineur harmonique.'),
mk('education-musicale','lutte-contre-les-drogues-et-l-alcool-dans-la-communaute','Lutte contre les drogues et l’alcool dans la communauté','Exploiter la musique comme support de prévention et de communication communautaire.'),
mk('education-musicale','chanson-populaire-periode-2','Chanson populaire — période 2','Interpréter et analyser une nouvelle chanson populaire selon les acquis rythmiques et mélodiques.'),
mk('education-musicale','la-musique-des-fetes-de-generations','La musique des fêtes de générations','Comprendre le rôle et les caractéristiques de musiques liées aux fêtes de générations.'),
mk('education-musicale','les-quatre-doubles-croches','Les quatre doubles croches','Lire, frapper et reconnaître la cellule rythmique étudiée.'),
mk('education-musicale','chanson-populaire-periode-3','Chanson populaire — période 3','Consolider interprétation, écoute et analyse à travers une chanson populaire.'),
mk('education-musicale','la-musique-rituelle-et-la-preservation-des-valeurs-traditionnelles','La musique rituelle et la préservation des valeurs traditionnelles','Relier pratiques musicales rituelles, contexte culturel et transmission des valeurs.'),
mk('education-musicale','le-temoin-en-temps-de-guerre','Le témoin en temps de guerre','Utiliser une activité musicale comme support de réflexion sur le témoignage et la protection en contexte de conflit.'),
mk('education-musicale','pratique-instrumentale-et-remediation','Pratique instrumentale et remédiation','Consolider les acquis par pratique instrumentale, écoute, correction et reprise ciblée.')
];