import {richLessons} from './rich-lessons';
export type CurriculumUnit={id:string;title:string;status:'rich'|'structured'|'reference';note?:string};
export type CurriculumSubject={id:string;name:string;official:boolean;progression:string;units:CurriculumUnit[];optional?:boolean;warning?:string};
const slug=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const U=(titles:string[],_legacyRich:string[]=[])=>titles.map(title=>({id:slug(title),title,status:'structured'} as CurriculumUnit));
export const curriculum3e:CurriculumSubject[]=[
{id:'mathematiques',name:'Mathématiques',official:true,progression:'2026-2027',units:U(['Calcul littéral','Propriétés de Thalès dans un triangle','Racines carrées','Triangle rectangle','Calcul numérique','Angles inscrits','Vecteurs','Équations et inéquations dans ℝ','Pyramides et cônes','Statistique','Coordonnées de vecteurs','Équations de droites','Applications affines','Équations et inéquations dans ℝ × ℝ'],['Calcul littéral'])},
{id:'francais',name:'Français',official:true,progression:'2026-2027',units:U(['Le dialogue oral','L’exposé oral','Le débat','Œuvre intégrale','Texte argumentatif — lecture','Article de journal — lecture','Le texte argumentatif','L’article de journal','Le résumé du texte argumentatif','La communication','La pronominalisation','L’adverbe et le groupe adverbial','L’infinitif et le participe','La coordination','L’expression des circonstances','Orthographe lexicale','Orthographe grammaticale'],['Le texte argumentatif','Le résumé du texte argumentatif','La communication','La pronominalisation','Orthographe grammaticale'])},
{id:'physique-chimie',name:'Physique-Chimie',official:true,progression:'2026-2027',units:U(['Masse et poids d’un corps','Les forces','Équilibre d’un solide soumis à deux forces','Travail et puissance mécaniques','Énergie mécanique','Électrolyse et synthèse de l’eau','Les alcanes','Les lentilles','Les défauts de l’œil et leurs corrections','Oxydation des corps purs simples','Réduction des oxydes','Solutions acides, basiques et neutres','Puissance et énergie électriques','Le conducteur ohmique'],['Masse et poids d’un corps','Les forces','Travail et puissance mécaniques','Puissance et énergie électriques','Solutions acides, basiques et neutres'])},
{id:'svt',name:'SVT',official:true,progression:'2026-2027',units:U(['Les aliments et l’Homme','La digestion des aliments','Le sang','La transfusion sanguine','La circulation sanguine','Les grossesses précoces et les moyens de prévention','L’infection au VIH','Les caractéristiques d’un sol','Les relations sols-plantes','La dégradation des sols','La protection et l’amélioration des sols'],['Les aliments et l’Homme','La digestion des aliments','Le sang','La circulation sanguine','La protection et l’amélioration des sols'])},
{id:'histoire-geographie',name:'Histoire-Géographie',official:true,progression:'2026-2027',units:U(['Le mouvement impérialiste et la colonisation en Côte d’Ivoire','L’accession de la Côte d’Ivoire à l’indépendance','Causes et caractères des crises sociopolitiques de l’Afrique indépendante','La crise rwandaise : de la guerre au génocide des Tutsi (1990-1994)','Les causes, les caractères et les conséquences de la Deuxième Guerre mondiale','L’Organisation des Nations Unies (ONU)','L’Union Africaine (UA)','Les atouts du développement économique de la Côte d’Ivoire','Les secteurs d’activités économiques de la Côte d’Ivoire','Les problèmes du développement économique de la Côte d’Ivoire','Étude économique de l’Afrique','La place de l’Afrique dans la mondialisation'],['L’accession de la Côte d’Ivoire à l’indépendance','Les causes, les caractères et les conséquences de la Deuxième Guerre mondiale','L’Organisation des Nations Unies (ONU)','Les secteurs d’activités économiques de la Côte d’Ivoire','La place de l’Afrique dans la mondialisation'])},
{id:'anglais',name:'Anglais',official:true,progression:'2026-2027',units:U(['Life at school','Women at work','Travelling','Fashion','City or village?','Human rights','Hygiene and health','Information and Communication Technologies'],['Life at school','Women at work','Travelling','Human rights','Hygiene and health'])},
{id:'edhc',name:'EDHC',official:true,progression:'2026-2027',units:U(['Les devoirs de parents et l’épanouissement de l’enfant','Les organisations humanitaires et la promotion de l’assistance aux populations en détresse','Les instruments et mécanismes de protection contre les violences faites aux personnes vulnérables','Partis politiques, institutions et paix sociale','Le vote et la participation citoyenne','L’impôt et le développement','L’utilisation rationnelle des biens publics','Le projet d’entreprise','Les alliances interethniques','Centres de santé et lutte contre l’automédication','Dépistage du VIH','Protection des parcs et réserves','Gestion rationnelle de l’eau'],['Le vote et la participation citoyenne','L’impôt et le développement','L’utilisation rationnelle des biens publics','Le projet d’entreprise','Gestion rationnelle de l’eau'])},
{id:'espagnol',name:'Espagnol LV2',official:true,progression:'2026-2027',optional:true,units:U(['La découverte du monde hispanique','La présentation des civilités','L’échange d’information','L’expression d’opinion','L’expression des goûts et des préférences','L’expression des sentiments','L’expression de l’ordre'])},
{id:'allemand',name:'Allemand LV2',official:true,progression:'2026-2027 · VORWÄRTS',optional:true,units:U(['Erster Kontakt','Begrüßen','Auf dem Markt','Eine Reise nach Man','Mein Lieblingsfach','Juliana','Ich lade dich ein','Mein Tageslauf'])},
{id:'tice',name:'TICE',official:true,progression:'2025-2026 — dernière progression détaillée retrouvée',warning:'Discipline officielle maintenue au collège à 1 h/semaine ; aucune progression TICE séparée repérée sur la page DPFC 2026-2027.',units:U(['Découverte d’un réseau informatique','Utilisation de document modèle','Le publipostage','Traitement de données statistiques avec un tableur','Traitement graphique des données avec un tableur','Découverte de l’environnement d’un logiciel de présentation','Conception d’une diapositive dynamique de présentation'])},
{id:'eps',name:'EPS',official:true,progression:'2026-2027',warning:'La programmation concrète dépend des infrastructures ; en 3e, priorité aux activités au programme du BEPC.',units:U(['Courses : endurance et vitesse','Gymnastique au sol','Activités de duel : lutte africaine / judo','Sauts : hauteur, longueur, triple saut','Lancers : lancer de poids','Sports collectifs : football'])},
{id:'arts-plastiques',name:'Arts plastiques',official:true,progression:'2026-2027',units:U(['Bande dessinée','Relation texte/image','Dépliant','Beauté corporelle et scarification','Équipements socioculturels','Gestion et protection de l’eau','Artisanat d’art et réduction du chômage','Art nègre et cubisme','Écriture artistique au début du 20ème siècle et naissance de l’art abstrait'])},
{id:'education-musicale',name:'Éducation musicale',official:true,progression:'2026-2027',units:U(['L’Abidjanaise à 2 voix','La tonalité de La mineur harmonique','La musique des masques Wè, Dan et Gouro','Les mines anti-personnel','Le demi-soupir croche','Chanson populaire — période 1','Rôle et importance de l’impôt','La tonalité de Ré mineur harmonique','Lutte contre les drogues et l’alcool dans la communauté','Chanson populaire — période 2','La musique des fêtes de générations','Les quatre doubles croches','Chanson populaire — période 3','La musique rituelle et la préservation des valeurs traditionnelles','Le témoin en temps de guerre','Pratique instrumentale et remédiation'])}
];
const richKeys=new Set(richLessons.map(l=>l.subject+':'+l.id));
export const effectiveCurriculum=curriculum3e.map(s=>({...s,units:s.units.map(u=>({...u,status:richKeys.has(s.id+':'+u.id)?'rich' as const:u.status}))}));
export const curriculumSubject=(id:string)=>effectiveCurriculum.find(s=>s.id===id);
export function coverage(){const subjects=effectiveCurriculum.length,units=effectiveCurriculum.reduce((n,s)=>n+s.units.length,0),rich=effectiveCurriculum.reduce((n,s)=>n+s.units.filter(u=>u.status==='rich').length,0);return{subjects,units,rich,percent:units?Math.round(rich/units*100):0}}
