import type {RichLesson} from './rich-lessons';
const mk=(id:string,title:string,why:string,simple:string,key:string,task:string,answer:string):RichLesson=>({id,subject:'edhc',title,why,prerequisites:['Lire une situation','Identifier droits, devoirs et responsabilités'],simple,detailed:simple+' L’objectif est de relier la règle ou la valeur à une situation réelle et de choisir un comportement responsable, légal et respectueux des autres.',analogy:'En EDHC, connaître une règle ne suffit pas : il faut savoir quelle décision prendre dans une situation concrète.',workedSteps:['Identifier le problème','Repérer les personnes concernées','Identifier droit, devoir ou valeur','Comparer les comportements possibles','Choisir et justifier une action responsable'],commonErrors:[{error:'Réciter une définition sans l’appliquer.',fix:'Ajoute toujours un exemple de comportement concret.'}],memoryTip:key,summary:[simple,key,'Justifier un comportement responsable'],remediation:[{errorTag:id,message:'La notion est connue mais son application reste floue.',action:'Travaille une situation concrète et explique pourquoi une action est préférable.'}],tests:[{id:id+'-1',type:'short',prompt:task,answer,explanation:'La réponse doit proposer une action cohérente et la justifier.',difficulty:2,errorTag:id},{id:id+'-2',type:'true_false',prompt:'Un comportement citoyen responsable tient compte de ses conséquences sur les autres.',options:['Vrai','Faux'],answer:'Vrai',explanation:'La responsabilité implique de considérer la collectivité.',difficulty:1}]});
export const edhcRichBatch:RichLesson[]=[
mk('les-devoirs-de-parents-et-l-epanouissement-de-l-enfant','Les devoirs des parents et l’épanouissement de l’enfant','Relier responsabilités parentales et développement de l’enfant.','Les parents ont des responsabilités de protection, entretien, éducation et accompagnement favorisant le développement de l’enfant.','Protection + éducation + accompagnement.','Cite deux devoirs parentaux favorisant l’épanouissement.','protéger et assurer l’éducation de l’enfant'),
mk('les-organisations-humanitaires-et-la-promotion-de-l-assistance-aux-populations-en-detresse','Les organisations humanitaires','Comprendre l’aide apportée aux populations en détresse.','Les organisations humanitaires interviennent pour protéger ou assister des personnes confrontées à des crises, catastrophes ou vulnérabilités.','Humanitaire = assistance impartiale aux personnes en détresse.','Donne un exemple de besoin humanitaire après une catastrophe.','soins, eau, nourriture ou abri'),
mk('les-instruments-et-mecanismes-de-protection-contre-les-violences-faites-aux-personnes-vulnerables','Protection des personnes vulnérables','Identifier les moyens de protection et de recours face aux violences.','La protection repose sur des règles, institutions, services et mécanismes permettant de prévenir, signaler et prendre en charge les violences.','Violence : ne pas banaliser · chercher protection et aide compétente.','Que faire face à une situation de violence envers une personne vulnérable ?','chercher de l’aide auprès d’un adulte ou service compétent et signaler la situation'),
mk('partis-politiques-institutions-et-paix-sociale','Partis politiques, institutions et paix sociale','Comprendre comment pluralisme et institutions doivent fonctionner dans le respect des règles.','Les partis participent à la vie politique ; les institutions organisent l’État et le respect des règles contribue à la paix sociale.','Désaccord politique ≠ violence.','Quel comportement favorise la paix en période de désaccord politique ?','respecter les règles et les autres opinions'),
mk('le-vote-et-la-participation-citoyenne','Le vote et la participation citoyenne','Comprendre la participation responsable à la vie publique.','Le vote est un moyen de participation citoyenne parmi d’autres, encadré par des règles et associé à des droits et devoirs.','Citoyenneté = droits + devoirs + participation responsable.','Cite une forme de participation citoyenne autre que le vote.','participer à une action communautaire ou au débat public'),
mk('l-impot-et-le-developpement','L’impôt et le développement','Relier contribution fiscale et financement collectif.','Les recettes fiscales participent au financement des services et investissements publics.','Impôt → ressources publiques → services collectifs.','Cite deux services pouvant être financés par les recettes publiques.','éducation et santé'),
mk('l-utilisation-rationnelle-des-biens-publics','L’utilisation rationnelle des biens publics','Comprendre pourquoi préserver un bien collectif est une responsabilité citoyenne.','Un bien public sert la collectivité ; sa dégradation crée un coût et réduit le service disponible pour tous.','Bien public = responsabilité partagée.','Que faire si un équipement scolaire est endommagé ?','le signaler et éviter d’aggraver la dégradation'),
mk('le-projet-d-entreprise','Le projet d’entreprise','Comprendre comment une idée répond à un besoin avec des ressources organisées.','Un projet d’entreprise identifie un besoin, propose une solution, des bénéficiaires ou clients et les ressources nécessaires.','Besoin → solution → bénéficiaire → ressources.','Donne un exemple de besoin auquel un petit projet scolaire pourrait répondre.','réponse ouverte cohérente'),
mk('les-alliances-interethniques','Les alliances interethniques','Comprendre des mécanismes sociaux pouvant favoriser cohésion et prévention des conflits.','Les alliances interethniques sont des relations historiques et sociales entre groupes pouvant favoriser solidarité, médiation et coexistence pacifique.','Connaître les traditions pour renforcer respect et cohésion.','Quel objectif social peuvent favoriser ces alliances ?','la cohésion et la paix sociale'),
mk('centres-de-sante-et-lutte-contre-l-automedication','Centres de santé et lutte contre l’automédication','Comprendre l’intérêt de recourir à des professionnels plutôt que prendre des médicaments au hasard.','Les centres de santé permettent évaluation, conseil et prise en charge par des professionnels ; l’automédication inadaptée peut présenter des risques.','Symptôme important ou persistant → professionnel de santé.','Pourquoi éviter de prendre au hasard un médicament conseillé par un ami ?','le traitement peut être inadapté ou risqué'),
mk('depistage-du-vih','Dépistage du VIH','Comprendre le rôle du dépistage dans la connaissance de son statut et la prévention.','Le dépistage permet de connaître son statut dans un cadre de santé approprié et facilite l’accès aux conseils et à la prise en charge.','Dépistage = information fiable + confidentialité + accompagnement.','À quoi sert principalement le dépistage du VIH ?','à connaître son statut'),
mk('protection-des-parcs-et-reserves','Protection des parcs et réserves','Relier protection des espaces naturels et préservation de la biodiversité.','Les parcs et réserves protègent habitats, espèces et patrimoines naturels contre différentes pressions.','Protéger habitat + espèces + ressources.','Cite une menace pour un espace protégé.','braconnage, déforestation ou pollution'),
mk('gestion-rationnelle-de-l-eau','Gestion rationnelle de l’eau','Adopter des comportements qui préservent une ressource essentielle.','La gestion rationnelle vise à limiter gaspillage et pollution et à favoriser un accès durable à l’eau.','Économiser · protéger · partager équitablement.','Cite deux gestes permettant d’économiser l’eau.','fermer les robinets inutiles et réparer les fuites')
];