import type {RichLesson} from './rich-lessons';
const mk=(id:string,title:string,why:string,vocab:string,grammar:string,task:string):RichLesson=>({id,subject:'anglais',title,why,prerequisites:['Basic sentence structure','Common everyday vocabulary'],simple:'This unit develops useful vocabulary about '+vocab+' and trains you to understand and communicate in realistic situations.',detailed:'Read for meaning first, then notice useful expressions and grammar. '+grammar+' Reuse the language in short spoken and written tasks instead of memorising isolated words.',analogy:'Learning English is like sport: understanding a rule helps, but progress comes from repeated use in different situations.',workedSteps:['Read or listen for the general idea','Find key words','Notice the target structure','Answer comprehension questions','Reuse the language in your own sentence'],commonErrors:[{error:'Translating every word before understanding the sentence.',fix:'Use context and key words to understand the main idea first.'}],memoryTip:'Understand → notice → reuse → recall later.',summary:['Key vocabulary: '+vocab,grammar,'Produce your own sentences'],remediation:[{errorTag:id,message:'The vocabulary or structure is not yet automatic.',action:'Use 5 short flashcards, then produce 3 new sentences without looking.'}],tests:[{id:id+'-1',type:'short',prompt:task,answer:'open answer',explanation:'Check meaning, target vocabulary and sentence structure.',difficulty:2,errorTag:id},{id:id+'-2',type:'true_false',prompt:'Using new vocabulary in your own sentence helps long-term learning.',options:['True','False'],answer:'True',explanation:'Active retrieval strengthens memory.',difficulty:1}]});
export const englishRichBatch:RichLesson[]=[
mk('life-at-school','Life at school','Talk about school life and experiences.','school subjects, routines and activities','Use present forms for routines and past forms for completed experiences.','Write three sentences about your school day.'),
mk('women-at-work','Women at work','Discuss occupations, responsibilities and equal opportunities.','jobs, work, skills and equality','Use can/can’t, should and opinion expressions to discuss opportunities.','Give two reasons why equal access to work matters.'),
mk('travelling','Travelling','Communicate during journeys and understand travel information.','transport, tickets, destinations and schedules','Practise questions with where, when, how much and what time.','Write a short dialogue asking for a departure time.'),
mk('fashion','Fashion','Describe clothes, preferences and responsible choices.','clothes, colours, materials and style','Use descriptive adjectives and expressions of preference.','Describe an outfit in four simple sentences.'),
mk('city-or-village','City or village?','Compare living environments and express preferences.','places, services, environment and daily life','Use comparatives and expressions such as more…than, less…than and because.','Compare city and village life with two differences.'),
mk('human-rights','Human rights','Talk about rights, duties and respectful behaviour.','rights, duties, freedom and responsibility','Use must, mustn’t, should and can to express obligation, prohibition, advice and permission.','Write two rights and two duties of a student.'),
mk('hygiene-and-health','Hygiene and health','Give simple prevention and hygiene advice.','body, hygiene, illness and prevention','Use should, must and imperative forms for advice and instructions.','Give four pieces of hygiene advice.'),
mk('information-and-communication-technologies','Information and Communication Technologies','Use vocabulary for digital tools and discuss safe, useful technology use.','devices, internet, messages, files and digital safety','Use present forms to describe uses and modals to express rules and advice.','Write three rules for responsible technology use.')
];