import type {RichLesson} from './rich-lessons';
const mk=(id:string,title:string,why:string,simple:string,steps:string[],error:string,fix:string,test:string,answer:string):RichLesson=>({id,subject:'francais',title,why,prerequisites:['Comprendre une consigne','Construire une phrase correcte'],simple,detailed:simple+' Il faut identifier l’intention, organiser les idées et choisir les outils de langue adaptés à la situation.',analogy:'Comme construire une maison : les idées sont les matériaux, mais l’ordre et les liens entre elles donnent une structure solide.',workedSteps:steps,commonErrors:[{error,fix}],memoryTip:'Lire la consigne → repérer l’objectif → organiser → produire → relire.',summary:[simple,'Organiser les idées','Justifier ou illustrer','Relire et corriger'],remediation:[{errorTag:id,message:error,action:fix}],tests:[{id:id+'-1',type:'short',prompt:test,answer,explanation:fix,difficulty:2,errorTag:id},{id:id+'-2',type:'true_false',prompt:'Une réponse efficace doit respecter précisément la consigne.',options:['Vrai','Faux'],answer:'Vrai',explanation:'La consigne détermine ce qui doit être produit et évalué.',difficulty:1}]});
export const frenchRichBatch:RichLesson[]=[
mk('le-dialogue-oral','Le dialogue oral','Savoir échanger clairement, écouter et adapter sa réponse.','Un dialogue est un échange organisé entre plusieurs personnes.',['Identifier la situation et les interlocuteurs','Écouter avant de répondre','Répondre au sujet','Employer un registre adapté','Conclure ou relancer naturellement'],'Parler sans tenir compte de la réponse précédente.','Reprends un mot ou une idée de ton interlocuteur avant d’ajouter ta réponse.','Donne deux règles d’un bon dialogue oral.','écouter et répondre au sujet'),
mk('l-expose-oral','L’exposé oral','Présenter des informations de façon claire devant un public.','Un exposé organise des informations autour d’un sujet et d’un plan.',['Comprendre le sujet','Rechercher les idées essentielles','Construire introduction, développement, conclusion','Préparer des notes courtes','Parler clairement sans lire tout le texte'],'Lire intégralement ses notes.','Transforme les phrases longues en mots-clés qui servent de repères.','Quelles sont les trois grandes parties d’un exposé ?','introduction, développement, conclusion'),
mk('le-debat','Le débat','Défendre une opinion tout en respectant les autres points de vue.','Débattre consiste à confronter des opinions à l’aide d’arguments.',['Identifier la question','Choisir une position','Formuler un argument','Écouter l’argument opposé','Répondre sans attaquer la personne'],'Confondre désaccord et attaque personnelle.','Critique l’idée avec des raisons, jamais la personne.','Quelle différence entre opinion et argument ?','un argument justifie une opinion'),
mk('oeuvre-integrale','Œuvre intégrale','Lire une œuvre complète permet de comprendre personnages, thèmes, évolution et intention globale.','Étudier une œuvre intégrale signifie relier les différentes parties au lieu de lire des extraits isolés.',['Identifier auteur, titre et genre','Repérer personnages et cadre','Suivre les événements essentiels','Identifier les thèmes','Justifier une interprétation par le texte'],'Résumer l’œuvre sans analyser ses thèmes.','Après le résumé, demande ce que l’œuvre fait comprendre ou questionne.','Que faut-il utiliser pour justifier une interprétation ?','des éléments précis du texte'),
mk('texte-argumentatif-lecture','Texte argumentatif — lecture','Reconnaître comment un auteur cherche à convaincre.','En lecture, on repère la thèse, les arguments, les exemples et les connecteurs.',['Lire la question avant le texte','Repérer le thème','Identifier la thèse','Associer arguments et exemples','Observer les connecteurs'],'Prendre un exemple pour la thèse.','Demande quelle idée générale tous les arguments cherchent à défendre.','Que cherche-t-on en premier dans un texte argumentatif ?','la thèse'),
mk('article-de-journal-lecture','Article de journal — lecture','Comprendre comment une information est organisée et présentée.','Un article informe autour d’un événement ou d’un sujet en répondant aux questions essentielles.',['Repérer titre et source','Identifier qui, quoi, où, quand','Distinguer faits et commentaires','Repérer les informations essentielles','Reformuler l’idée principale'],'Confondre fait et opinion du journaliste.','Un fait peut être vérifié ; une opinion exprime un jugement.','Cite quatre questions utiles pour comprendre un événement.','qui, quoi, où, quand'),
mk('le-texte-argumentatif','Le texte argumentatif','Défendre une idée de manière logique et convaincante.','Une argumentation articule thèse, arguments, exemples et connecteurs.',['Analyser le sujet','Choisir une thèse','Trouver des arguments distincts','Illustrer chaque argument','Conclure clairement'],'Donner une opinion sans la justifier.','Après chaque opinion, demande : pourquoi ?','À quoi sert un argument ?','à justifier la thèse'),
mk('l-article-de-journal','L’article de journal','Rédiger une information claire pour un lecteur.','Un article hiérarchise les informations et adopte un style adapté au public.',['Choisir un titre informatif','Présenter l’essentiel dès le début','Répondre aux questions de base','Développer les détails','Relire les faits et la langue'],'Commencer par des détails secondaires.','Place les informations indispensables au début.','Que doit faire un bon titre de presse ?','annoncer clairement le sujet'),
mk('le-resume-du-texte-argumentatif','Le résumé du texte argumentatif','Restituer fidèlement l’essentiel avec moins de mots.','Résumer consiste à conserver thèse et arguments principaux sans commentaire personnel.',['Lire entièrement','Repérer thèse et arguments','Supprimer répétitions et exemples secondaires','Reformuler','Vérifier fidélité et longueur'],'Ajouter son avis personnel.','Un résumé restitue le texte : il ne débat pas avec l’auteur.','Peut-on ajouter son opinion dans un résumé fidèle ?','non'),
mk('la-communication','La communication','Comprendre qui parle, à qui, comment et pourquoi.','Une situation de communication comprend émetteur, récepteur, message, canal, code et contexte.',['Identifier l’émetteur','Identifier le récepteur','Repérer le message','Identifier canal et code','Comprendre l’intention et le contexte'],'Confondre canal et message.','Le message est ce qui est dit ; le canal est le moyen utilisé pour le transmettre.','Dans un appel téléphonique, quel est le canal ?','le téléphone'),
mk('la-pronominalisation','La pronominalisation','Éviter les répétitions et construire des phrases plus fluides.','Pronominaliser consiste à remplacer un groupe nominal par un pronom adapté.',['Repérer le groupe à remplacer','Identifier sa fonction','Choisir le pronom','Placer correctement le pronom','Vérifier genre et nombre'],'Choisir un pronom uniquement selon le genre.','Vérifie aussi la fonction du groupe dans la phrase.','Remplace « Awa » dans « Je vois Awa ».','Je la vois'),
mk('l-adverbe-et-le-groupe-adverbial','L’adverbe et le groupe adverbial','Préciser le sens d’un verbe, adjectif ou autre élément.','L’adverbe est invariable et peut préciser manière, temps, lieu, quantité ou intensité.',['Repérer le mot précisé','Identifier l’adverbe','Déterminer sa valeur','Vérifier qu’il est invariable'],'Accorder un adverbe comme un adjectif.','Un adverbe est normalement invariable.','Dans « Il parle doucement », quel mot précise le verbe ?','doucement'),
mk('l-infinitif-et-le-participe','L’infinitif et le participe','Distinguer des formes verbales souvent confondues à l’écrit.','L’infinitif nomme l’action ; les participes entrent notamment dans les temps composés ou peuvent avoir un emploi adjectival.',['Identifier le verbe','Observer son environnement','Tester avec un autre verbe','Choisir infinitif ou participe','Vérifier l’accord si nécessaire'],'Confondre -er et -é.','Remplace mentalement par vendre/vendu : la différence s’entend mieux.','Dans « Il a mangé », mangé est quelle forme ?','participe passé'),
mk('la-coordination','La coordination','Relier des mots ou propositions de même fonction.','La coordination relie des éléments grâce notamment à mais, ou, et, donc, or, ni, car.',['Repérer les éléments reliés','Identifier le coordonnant','Comprendre la relation logique','Vérifier l’équilibre de la phrase'],'Employer un coordonnant sans relation logique.','Demande quel lien existe : addition, opposition, cause, conséquence…','Dans « Il travaille car il veut réussir », quel lien exprime car ?','cause'),
mk('l-expression-des-circonstances','L’expression des circonstances','Préciser temps, cause, conséquence, but, condition ou opposition.','Les circonstances indiquent dans quelles conditions se déroule une action ou s’établit une relation logique.',['Repérer les propositions','Identifier le connecteur','Nommer la relation logique','Reformuler avec un autre outil si possible'],'Identifier la relation seulement grâce à un mot appris par cœur.','Lis le sens de toute la phrase : un même mot peut changer de valeur selon le contexte.','Dans « Il révise afin de réussir », quelle circonstance ?','but'),
mk('orthographe-lexicale','Orthographe lexicale','Écrire correctement les mots et développer des stratégies de vérification.','L’orthographe lexicale concerne la forme propre des mots, leurs familles et certaines régularités.',['Identifier le mot difficile','Chercher sa famille','Repérer préfixe/radical/suffixe','Utiliser le dictionnaire en cas de doute','Mémoriser la forme correcte'],'Deviner uniquement selon la prononciation.','Utilise la famille du mot et le dictionnaire offline.','Quel outil de l’application aide à vérifier un mot ?','le dictionnaire'),
mk('orthographe-grammaticale','Orthographe grammaticale','Maîtriser les accords produits par les relations entre les mots.','L’orthographe grammaticale concerne notamment accord sujet-verbe et accords dans le groupe nominal.',['Repérer le verbe','Trouver son sujet','Repérer noms et adjectifs','Faire les accords','Relire en cherchant chaque donneur d’accord'],'Accorder avec le mot le plus proche au lieu du donneur d’accord.','Pose la question « qui est-ce qui ? » pour trouver le sujet du verbe.','Corrige : « Les élèves travaille ».','Les élèves travaillent')
];