import type {RichLesson} from './rich-lessons';
const mk=(id:string,title:string,why:string,simple:string,key:string,test:string,answer:string):RichLesson=>({id,subject:'histoire-geographie',title,why,prerequisites:['Situer dans le temps et l’espace','Distinguer cause, fait et conséquence','Lire un document'],simple,detailed:simple+' Pour analyser correctement, il faut identifier les acteurs, les causes, les étapes, les conséquences et replacer les faits dans leur contexte.',analogy:'En histoire-géographie, construis une chaîne : contexte → causes → faits/organisation → conséquences → portée.',workedSteps:['Identifier le sujet et la période ou l’espace','Repérer les acteurs et notions','Classer causes et faits','Identifier les conséquences','Justifier avec un repère ou document'],commonErrors:[{error:'Réciter des dates ou notions sans expliquer les liens.',fix:'Relie chaque repère à une cause, un fait ou une conséquence.'}],memoryTip:key,summary:[simple,key,'Toujours justifier avec un repère précis'],remediation:[{errorTag:id,message:'Les repères sont connus mais pas reliés.',action:'Construis une mini-frise ou un schéma causes→faits→conséquences.'}],tests:[{id:id+'-1',type:'short',prompt:test,answer,explanation:'La réponse doit contenir le repère demandé et son sens.',difficulty:2,errorTag:id},{id:id+'-2',type:'true_false',prompt:'Une bonne réponse d’histoire-géographie doit relier les faits plutôt que seulement les énumérer.',options:['Vrai','Faux'],answer:'Vrai',explanation:'L’explication des relations est essentielle.',difficulty:1}]});
export const hgRichBatch:RichLesson[]=[
mk('le-mouvement-imperialiste-et-la-colonisation-en-cote-d-ivoire','Le mouvement impérialiste et la colonisation en Côte d’Ivoire','Comprendre comment la Côte d’Ivoire est intégrée à l’empire colonial français.','L’impérialisme européen du XIXe siècle entraîne conquêtes, résistances, mise en place d’une administration coloniale et transformations économiques et sociales.','Conquête → résistances → administration → transformations.','Que faut-il distinguer entre conquête et colonisation ?','la conquête est la prise de contrôle ; la colonisation organise durablement la domination'),
mk('l-accession-de-la-cote-d-ivoire-a-l-independance','L’accession de la Côte d’Ivoire à l’indépendance','Comprendre le processus politique menant à la souveraineté.','Après 1945, les évolutions politiques, les revendications africaines et la décolonisation conduisent la Côte d’Ivoire à l’indépendance le 7 août 1960.','Repère central : 7 août 1960.','Date de l’indépendance de la Côte d’Ivoire ?','7 août 1960'),
mk('causes-et-caracteres-des-crises-sociopolitiques-de-l-afrique-independante','Crises sociopolitiques de l’Afrique indépendante','Analyser pourquoi certains États africains connaissent instabilité et conflits.','Les crises peuvent combiner fragilités institutionnelles, rivalités politiques, difficultés économiques, tensions sociales et interventions extérieures.','Éviter la cause unique : les crises sont multifactorielles.','Pourquoi faut-il éviter une explication par une seule cause ?','plusieurs facteurs politiques, économiques et sociaux peuvent se combiner'),
mk('la-crise-rwandaise-de-la-guerre-au-genocide-des-tutsi-1990-1994','La crise rwandaise : de la guerre au génocide des Tutsi (1990-1994)','Comprendre l’enchaînement qui mène d’une crise politique et militaire au génocide des Tutsi.','Entre 1990 et 1994, guerre, radicalisation politique et propagande précèdent le génocide des Tutsi de 1994, qui cause des massacres de masse.','1994 : génocide des Tutsi au Rwanda.','Quel crime de masse marque le Rwanda en 1994 ?','le génocide des Tutsi'),
mk('les-causes-les-caracteres-et-les-consequences-de-la-deuxieme-guerre-mondiale','La Deuxième Guerre mondiale','Comprendre un conflit mondial et ses conséquences majeures.','La guerre de 1939-1945 résulte de tensions internationales et des politiques expansionnistes ; elle devient mondiale, totale et extrêmement meurtrière.','1939-1945 · guerre mondiale · violence de masse · nouvel ordre international.','Quelles sont les dates de la Deuxième Guerre mondiale ?','1939-1945'),
mk('l-organisation-des-nations-unies-onu','L’Organisation des Nations Unies (ONU)','Comprendre pourquoi et comment les États organisent la coopération internationale.','Créée en 1945, l’ONU vise notamment paix et sécurité internationales, coopération et promotion des droits humains.','ONU : 1945 · paix · coopération · droits humains.','En quelle année l’ONU est-elle créée ?','1945'),
mk('l-union-africaine-ua','L’Union Africaine (UA)','Comprendre l’organisation de coopération continentale africaine.','L’Union Africaine favorise coopération, intégration, paix et développement entre États africains et succède à l’OUA.','UA : coopération et intégration africaines.','Quelle organisation continentale succède à l’OUA ?','Union Africaine'),
mk('les-atouts-du-developpement-economique-de-la-cote-d-ivoire','Atouts du développement économique de la Côte d’Ivoire','Identifier les ressources et facteurs favorables au développement.','La Côte d’Ivoire dispose notamment de ressources agricoles et minières, d’infrastructures, d’une façade maritime, d’une population active et d’une position régionale importante.','Atout ≠ résultat : une ressource doit être valorisée.','Cite deux catégories d’atouts économiques ivoiriens.','ressources naturelles et infrastructures'),
mk('les-secteurs-d-activites-economiques-de-la-cote-d-ivoire','Secteurs d’activités économiques de la Côte d’Ivoire','Comprendre l’organisation de l’économie en secteurs.','Le primaire exploite les ressources, le secondaire les transforme et le tertiaire fournit des services.','Primaire → produire · secondaire → transformer · tertiaire → servir.','Une usine de transformation du cacao appartient à quel secteur ?','secondaire'),
mk('les-problemes-du-developpement-economique-de-la-cote-d-ivoire','Problèmes du développement économique de la Côte d’Ivoire','Identifier les obstacles et les réponses possibles au développement.','Les défis peuvent concerner transformation locale insuffisante, inégalités, emploi, infrastructures, dépendances et durabilité environnementale.','Diagnostic → causes → conséquences → solutions.','Pourquoi la transformation locale peut-elle être importante ?','elle peut créer davantage de valeur et d’emplois localement'),
mk('etude-economique-de-l-afrique','Étude économique de l’Afrique','Analyser ressources, activités, échanges et disparités économiques du continent.','L’Afrique possède d’importantes ressources et des économies diverses, mais connaît de fortes disparités de transformation, infrastructures et intégration.','Ne jamais parler de l’Afrique comme d’une économie unique.','Pourquoi faut-il parler de diversité économique africaine ?','les pays et régions ont des ressources, activités et niveaux de développement différents'),
mk('la-place-de-l-afrique-dans-la-mondialisation','La place de l’Afrique dans la mondialisation','Analyser les échanges mondiaux, les opportunités et les dépendances.','L’Afrique participe aux flux mondiaux par matières premières, produits, services, capitaux, migrations et innovations, avec des positions très diverses.','Mondialisation = flux + interdépendances + rapports de force.','Cite un moyen d’augmenter la valeur créée localement en Afrique.','transformer davantage les matières premières localement')
];