export type LessonContent={id:string;title:string;eyebrow:string;summary:string;objectives:string[];concepts:{title:string;text:string;formula?:string;example?:string}[];activities:{id:string;skill:string;prompt:string;answers:string[];display:string;hint:string;explanation:string}[]};
const L=(id:string,title:string,n:number,summary:string,objectives:string[],concept:{title:string;text:string;formula?:string;example?:string},activity:{skill:string;prompt:string;answers:string[];display:string;hint:string;explanation:string}):LessonContent=>({id,title,eyebrow:`LEÇON ${String(n).padStart(2,'0')} · MATHÉMATIQUES`,summary,objectives,concepts:[concept],activities:[{id:id+'-1',...activity}]});
export const mathsLessons:LessonContent[]=[
L('calcul-litteral','Calcul littéral',1,'Développer, réduire, factoriser et simplifier des expressions.',['Développer','Réduire','Factoriser','Simplifier'],{title:'Distributivité',text:'Développer supprime les parenthèses; factoriser effectue l’opération inverse.',formula:'k(a+b)=ka+kb',example:'2(x+3)+4x=6x+6'},{skill:'Développer une expression littérale',prompt:'Développe et réduis A = 3(x + 4) - 2(x - 1).',answers:['x+14'],display:'A = x + 14',hint:'Distribue 3 puis -2.',explanation:'3x+12-2x+2=x+14.'}),
L('thales','Propriétés de Thalès dans un triangle',2,'Calculer des longueurs et démontrer un parallélisme.',['Reconnaître une configuration','Calculer une distance','Utiliser la réciproque'],{title:'Thalès',text:'Dans une configuration de Thalès, les longueurs correspondantes sont proportionnelles.',formula:'AM/AB = AN/AC',example:'6/10 = AN/15 → AN=9'},{skill:'Calculer des distances avec Thalès',prompt:'AB=10 cm, AM=6 cm, AC=15 cm et MN∥BC. Calcule AN.',answers:['9','9cm'],display:'AN = 9 cm',hint:'Écris AM/AB=AN/AC.',explanation:'AN=15×6/10=9 cm.'}),
L('racines-carrees','Racines carrées',3,'Simplifier et calculer avec des racines carrées.',['Simplifier une racine','Calculer','Rationaliser'],{title:'Carré parfait',text:'On extrait d’une racine les facteurs qui sont des carrés parfaits.',formula:'√(a²b)=a√b',example:'√50=5√2'},{skill:'Calculer avec des racines carrées',prompt:'Simplifie √50 - 2√8.',answers:['√2','sqrt2'],display:'√2',hint:'√50=5√2 et √8=2√2.',explanation:'5√2-4√2=√2.'}),
L('triangle-rectangle','Triangle rectangle',4,'Utiliser Pythagore et la trigonométrie dans un triangle rectangle.',['Pythagore','Réciproque','Trigonométrie'],{title:'Pythagore',text:'Dans un triangle rectangle, le carré de l’hypoténuse est la somme des carrés des deux autres côtés.',formula:'c²=a²+b²',example:'3²+4²=5²'},{skill:'Utiliser le théorème de Pythagore',prompt:'Un triangle rectangle a pour côtés de l’angle droit 6 cm et 8 cm. Calcule l’hypoténuse.',answers:['10','10cm'],display:'10 cm',hint:'Calcule √(6²+8²).',explanation:'√(36+64)=√100=10 cm.'}),
L('calcul-numerique','Calcul numérique',5,'Comparer, encadrer et travailler avec des intervalles de nombres réels.',['Lire un intervalle','Comparer','Encadrer'],{title:'Intervalle',text:'Un intervalle décrit un ensemble continu de nombres réels entre deux bornes.',formula:'x∈[a;b] ⇔ a≤x≤b',example:'x∈[2;5] signifie 2≤x≤5'},{skill:'Traduire un intervalle',prompt:'Écris sous forme d’inégalités : x ∈ [-2 ; 4].',answers:['-2≤x≤4','-2<=x<=4'],display:'-2 ≤ x ≤ 4',hint:'Les crochets indiquent que les bornes sont incluses.',explanation:'x est supérieur ou égal à -2 et inférieur ou égal à 4.'}),
L('angles-inscrits','Angles inscrits',6,'Relier angles inscrits, angles au centre et arcs interceptés.',['Identifier un angle inscrit','Calculer un angle'],{title:'Angle inscrit',text:'Un angle inscrit mesure la moitié de l’angle au centre interceptant le même arc.',formula:'angle inscrit = angle au centre / 2',example:'Angle au centre 80° → angle inscrit 40°'},{skill:'Calculer un angle inscrit',prompt:'Un angle au centre mesure 100°. Quel est l’angle inscrit interceptant le même arc ?',answers:['50','50°'],display:'50°',hint:'Divise l’angle au centre par 2.',explanation:'100°/2=50°.'}),
L('vecteurs','Vecteurs',7,'Manipuler somme, différence, colinéarité et relations vectorielles.',['Additionner des vecteurs','Reconnaître la colinéarité'],{title:'Relation de Chasles',text:'La somme de deux vecteurs consécutifs donne le vecteur reliant le départ à l’arrivée.',formula:'AB⃗ + BC⃗ = AC⃗',example:'Le chemin A→B puis B→C équivaut à A→C.'},{skill:'Utiliser la relation de Chasles',prompt:'Complète : AB⃗ + BC⃗ = ?',answers:['ac','ac⃗'],display:'AC⃗',hint:'Relie directement le point de départ au point d’arrivée.',explanation:'Par la relation de Chasles : AB⃗+BC⃗=AC⃗.'}),
L('equations-r','Équations et inéquations dans ℝ',8,'Résoudre des équations et inéquations du premier degré.',['Résoudre une équation','Résoudre une inéquation'],{title:'Isoler l’inconnue',text:'On effectue la même opération dans les deux membres.',formula:'ax+b=c',example:'3x-7=11 → x=6'},{skill:'Résoudre une équation du premier degré',prompt:'Résous 3x - 7 = 11.',answers:['6','x=6'],display:'x = 6',hint:'Ajoute 7 aux deux membres.',explanation:'3x=18 puis x=6.'}),
L('pyramides-cones','Pyramides et cônes',9,'Calculer volumes, aires et réductions de solides.',['Identifier les éléments','Calculer un volume'],{title:'Volume d’une pyramide',text:'Le volume vaut un tiers du produit de l’aire de base par la hauteur.',formula:'V=(Aire base × h)/3',example:'Base 12 cm², h=5 cm → V=20 cm³'},{skill:'Calculer le volume d’une pyramide',prompt:'Une pyramide a une base de 18 cm² et une hauteur de 6 cm. Calcule son volume.',answers:['36','36cm3','36cm³'],display:'36 cm³',hint:'Utilise V=A×h/3.',explanation:'18×6/3=36 cm³.'}),
L('statistique','Statistique',10,'Organiser et interpréter des données statistiques.',['Calculer une moyenne','Déterminer une médiane','Lire un diagramme'],{title:'Moyenne',text:'La moyenne est la somme des valeurs divisée par leur nombre.',formula:'m=(x₁+…+xₙ)/n',example:'(8+10+12)/3=10'},{skill:'Calculer une moyenne',prompt:'Calcule la moyenne de 8, 10 et 12.',answers:['10'],display:'10',hint:'Additionne puis divise par 3.',explanation:'30/3=10.'}),
L('coordonnees-vecteurs','Coordonnées de vecteurs',11,'Calculer coordonnées, milieux et distances dans un repère.',['Coordonnées d’un vecteur','Milieu','Distance'],{title:'Coordonnées d’un vecteur',text:'On soustrait les coordonnées du point de départ à celles du point d’arrivée.',formula:'AB⃗=(xB-xA ; yB-yA)',example:'A(1;2), B(4;6) → AB⃗=(3;4)'},{skill:'Calculer les coordonnées d’un vecteur',prompt:'A(1;2) et B(4;6). Donne les coordonnées de AB⃗.',answers:['(3;4)','3;4','(3,4)'],display:'AB⃗ = (3 ; 4)',hint:'Fais xB-xA puis yB-yA.',explanation:'(4-1 ; 6-2)=(3 ; 4).'}),
L('equations-droites','Équations de droites',12,'Déterminer et exploiter une équation de droite.',['Coefficient directeur','Équation de droite','Parallélisme'],{title:'Forme réduite',text:'Une droite non verticale peut s’écrire y=mx+p.',formula:'y=mx+p',example:'y=2x+1 a pour coefficient directeur 2'},{skill:'Identifier un coefficient directeur',prompt:'Quel est le coefficient directeur de y = 3x - 5 ?',answers:['3'],display:'3',hint:'Dans y=mx+p, cherche m.',explanation:'m=3.'}),
L('applications-affines','Applications affines',13,'Étudier et représenter les applications de la forme ax+b.',['Calculer une image','Déterminer une expression','Étudier les variations'],{title:'Application affine',text:'Une application affine associe à x la valeur ax+b.',formula:'f(x)=ax+b',example:'f(x)=2x+3 → f(4)=11'},{skill:'Calculer une image',prompt:'Soit f(x)=2x+3. Calcule f(4).',answers:['11'],display:'f(4) = 11',hint:'Remplace x par 4.',explanation:'2×4+3=11.'}),
L('equations-rxr','Équations et inéquations dans ℝ × ℝ',14,'Résoudre des systèmes de deux équations à deux inconnues.',['Vérifier un couple','Résoudre un système','Interpréter graphiquement'],{title:'Système',text:'Une solution doit satisfaire simultanément les deux équations.',formula:'{ ax+by=c ; a′x+b′y=c′ }',example:'x+y=5 et x-y=1 → x=3, y=2'},{skill:'Résoudre un système simple',prompt:'Résous : x+y=5 et x-y=1. Donne x.',answers:['3','x=3'],display:'x = 3 et y = 2',hint:'Additionne les deux équations.',explanation:'2x=6 donc x=3; puis y=2.'})
];
export const lessonById=(id:string)=>mathsLessons.find(l=>l.id===id);
