import type {RichLesson} from './rich-lessons';
const mk=(id:string,title:string,why:string,simple:string,detailed:string,formula:string,example:string,error:string,fix:string,testPrompt:string,testAnswer:string):RichLesson=>({id,subject:'mathematiques',title,why,prerequisites:['Calcul numérique de base','Lecture attentive de la consigne'],simple,detailed,analogy:example,workedSteps:[formula,example,'Identifier les données utiles','Appliquer la propriété','Vérifier le résultat'],commonErrors:[{error,fix}],memoryTip:formula,summary:[simple,formula,'Toujours vérifier le résultat'],remediation:[{errorTag:id,message:error,action:fix}],tests:[{id:id+'-mcq',type:'short',prompt:testPrompt,answer:testAnswer,explanation:fix,difficulty:2,errorTag:id},{id:id+'-tf',type:'true_false',prompt:'Je dois toujours vérifier les conditions avant d’appliquer la propriété.',options:['Vrai','Faux'],answer:'Vrai',explanation:'Une formule ou propriété n’est valable que lorsque ses conditions sont satisfaites.',difficulty:1}]});
export const mathsRichBatch:RichLesson[]=[
mk('thales','Propriétés de Thalès dans un triangle','Calculer des longueurs inaccessibles et démontrer un parallélisme.','Dans une configuration de Thalès, des côtés correspondants sont proportionnels.','Si M∈[AB], N∈[AC] et MN∥BC, alors AM/AB=AN/AC=MN/BC. La réciproque permet de démontrer un parallélisme lorsque les rapports et alignements conviennent.','Même ordre des sommets → mêmes rapports.','Une photo agrandie conserve toutes ses proportions.','Mélanger les côtés correspondants.','Écris les deux triangles dans le même ordre avant les rapports.','AM=4, AB=10, AC=15, MN∥BC. AN=?','6'),
mk('triangle-rectangle','Triangle rectangle','Calculer des distances et angles dans de nombreuses situations concrètes.','Pythagore relie les trois côtés d’un triangle rectangle.','Si c est l’hypoténuse : c²=a²+b². La réciproque peut prouver qu’un triangle est rectangle. Sinus, cosinus et tangente relient côtés et angles aigus.','Hypoténuse² = côté² + côté².','Une échelle contre un mur forme un triangle rectangle avec le sol.','Choisir le mauvais côté comme hypoténuse.','Cherche l’angle droit : l’hypoténuse est le côté situé en face.','Côtés de l’angle droit 6 et 8. Hypoténuse=?','10'),
mk('calcul-numerique','Calcul numérique','Comparer, encadrer et représenter précisément des nombres réels.','Un intervalle représente tous les nombres entre deux bornes.','On traduit intervalles et inégalités, calcule intersections/réunions et utilise les règles d’ordre. Multiplier ou diviser une inégalité par un nombre négatif inverse son sens.','Négatif × inégalité → signe inversé.','Un intervalle est une zone autorisée sur une droite graduée.','Oublier d’inverser le signe avec un nombre négatif.','À chaque multiplication ou division par un négatif, retourne < et >.','Si -2x<6, x est ?','x>-3'),
mk('angles-inscrits','Angles inscrits','Déterminer des angles dans un cercle sans les mesurer directement.','Un angle inscrit mesure la moitié de l’angle au centre interceptant le même arc.','Deux angles inscrits interceptant le même arc ont la même mesure. L’angle au centre correspondant vaut le double.','Centre = double ; inscrit = moitié.','Le même arc est vu plus largement depuis le centre que depuis le bord.','Utiliser des angles qui n’interceptent pas le même arc.','Repère d’abord les deux extrémités de l’arc.','Angle au centre=100°. Angle inscrit=?','50'),
mk('vecteurs','Vecteurs','Décrire des déplacements et démontrer alignement ou parallélisme.','Un vecteur possède direction, sens et longueur.','La relation de Chasles permet d’additionner des déplacements : AB⃗+BC⃗=AC⃗. La colinéarité sert à démontrer alignement et parallélisme.','AB⃗+BC⃗=AC⃗.','Un vecteur est une instruction de déplacement de A vers B.','Confondre AB⃗ et BA⃗.','Lis toujours la flèche comme départ → arrivée.','AB⃗+BC⃗=?','AC'),
mk('equations-r','Équations et inéquations dans ℝ','Trouver une valeur inconnue à partir de contraintes.','Résoudre revient à isoler l’inconnue sans casser l’égalité.','On effectue la même opération dans les deux membres. Pour une inéquation, une multiplication/division par un négatif inverse le signe.','Équation = balance.','Faire la même opération des deux côtés revient à garder une balance en équilibre.','Déplacer un terme sans comprendre le changement de signe.','Écris l’opération effectuée dans les deux membres.','3x-7=11. x=?','6'),
mk('pyramides-cones','Pyramides et cônes','Calculer des capacités et dimensions de solides usuels.','Le volume vaut aire de base × hauteur ÷ 3.','Pour une pyramide V=A_base×h/3. Pour un cône A_base=πr², donc V=πr²h/3. La hauteur est perpendiculaire à la base.','V=A_base×h/3.','Trois pyramides de même base et hauteur remplissent le prisme correspondant.','Oublier de diviser par 3.','Écris Base × hauteur puis ajoute systématiquement ÷3.','Base=18 cm², h=6 cm. V=?','36'),
mk('statistique','Statistique','Résumer et interpréter des séries de données.','Moyenne, médiane et fréquences décrivent une série sous différents angles.','La moyenne utilise toutes les valeurs. La médiane partage une série ordonnée en deux groupes. Les fréquences cumulées et diagrammes aident à interpréter les distributions.','Médiane = milieu après rangement.','Une statistique raconte une classe entière sans citer chaque élève.','Chercher la médiane avant de ranger les valeurs.','Ordonne toujours la série avant de chercher son milieu.','Médiane de 2,9,4,7,5=?','5'),
mk('coordonnees-vecteurs','Coordonnées de vecteurs','Transformer des problèmes géométriques en calculs.','AB⃗ se calcule par arrivée moins départ.','AB⃗=(xB-xA ; yB-yA). Les coordonnées permettent aussi de calculer milieu, distance, colinéarité et orthogonalité.','Arrivée − départ.','Sur une carte, compte le déplacement horizontal puis vertical de A vers B.','Faire A-B au lieu de B-A.','Répète : arrivée moins départ.','A(1;2), B(4;6). AB⃗=?','(3;4)'),
mk('equations-droites','Équations de droites','Décrire algébriquement une droite et étudier parallélisme/perpendicularité.','Une droite non verticale peut s’écrire y=mx+p.','m est le coefficient directeur et p l’ordonnée à l’origine. Des coefficients directeurs permettent de comparer des directions.','y=mx+p.','m indique la pente d’une route et p son point de départ sur l’axe vertical.','Confondre m et p.','Dans y=mx+p, m multiplie x.','Dans y=3x-5, m=?','3'),
mk('applications-affines','Applications affines','Modéliser une quantité qui évolue selon une règle régulière.','Une application affine s’écrit f(x)=ax+b.','a contrôle la variation et b la valeur initiale. On calcule images, antécédents et représentation graphique.','f(x)=ax+b.','Un taxi peut coûter une prise en charge b plus a francs par kilomètre.','Confondre image et antécédent.','Image : on connaît x et on calcule f(x).','f(x)=2x+3. f(4)=?','11'),
mk('equations-rxr','Équations et inéquations dans ℝ × ℝ','Résoudre des problèmes comportant deux inconnues liées.','Un système demande un couple qui satisfait toutes les équations en même temps.','On peut résoudre par substitution, combinaison ou graphiquement. Pour des inéquations, les solutions deviennent des régions du plan.','Une solution satisfait toutes les lignes.','Deux contraintes sont comme deux indices qui doivent désigner le même couple.','S’arrêter après avoir satisfait une seule équation.','Remplace le couple trouvé dans toutes les équations.','x+y=5 et x-y=1. x=?','3')
];