export type TestItem={id:string;type:'mcq'|'true_false'|'fill'|'numeric'|'order'|'short';prompt:string;options?:string[];answer:string|string[];explanation:string;difficulty:1|2|3|4;errorTag?:string};
export type RichLesson={id:string;subject:string;title:string;why:string;prerequisites:string[];simple:string;detailed:string;analogy:string;workedSteps:string[];commonErrors:{error:string;fix:string}[];memoryTip:string;summary:string[];tests:TestItem[]};
export const richLessons:RichLesson[]=[
{id:'calcul-litteral',subject:'mathematiques',title:'Calcul littéral',why:'Le calcul littéral permet de représenter une situation avec des lettres, de simplifier des calculs et de résoudre ensuite des équations.',prerequisites:['Priorités opératoires','Nombres relatifs','Distributivité simple'],simple:'Une lettre comme x représente un nombre que l’on ne connaît pas encore ou qui peut changer. On manipule alors l’expression en respectant exactement les mêmes règles qu’avec des nombres.',detailed:'Développer transforme un produit en somme : k(a+b)=ka+kb. Réduire rassemble uniquement les termes de même nature. Factoriser fait le chemin inverse : on repère un facteur commun et on transforme une somme en produit. Ces transformations conservent la valeur de l’expression.',analogy:'Imagine des sacs identiques : 3(x+2) signifie trois sacs contenant chacun x objets et 2 objets supplémentaires. En ouvrant les trois sacs, on obtient 3x+6.',workedSteps:['Expression : 3(x+4)-2(x-1)','Distribuer 3 : 3x+12-2(x-1)','Distribuer -2 : 3x+12-2x+2','Regrouper : (3x-2x)+(12+2)','Résultat : x+14'],commonErrors:[{error:'Oublier de distribuer le signe moins.',fix:'Considère -2 comme un nombre complet : -2×x et -2×(-1).'},{error:'Additionner 3x et 12.',fix:'On ne réduit que les termes de même nature : x avec x, nombres avec nombres.'}],memoryTip:'Développer = ouvrir les parenthèses. Factoriser = reconstruire une parenthèse.',summary:['Distribuer à tous les termes','Respecter les signes','Regrouper uniquement les termes semblables','Toujours vérifier avec une valeur simple de x'],tests:[
{id:'cl-mcq-1',type:'mcq',prompt:'Quelle expression est égale à 2(x+5) ?',options:['2x+5','2x+10','x+10','7x'],answer:'2x+10',explanation:'2 multiplie x ET 5.',difficulty:1,errorTag:'distributivite'},
{id:'cl-fill-1',type:'fill',prompt:'Complète : 4(x-3) = 4x + ___',answer:'-12',explanation:'4×(-3)=-12.',difficulty:1,errorTag:'signes'},
{id:'cl-tf-1',type:'true_false',prompt:'3x + 5x = 8x.',options:['Vrai','Faux'],answer:'Vrai',explanation:'Ce sont deux termes de même nature.',difficulty:1},
{id:'cl-short-1',type:'short',prompt:'Développe et réduis 3(x+4)-2(x-1).',answer:'x+14',explanation:'3x+12-2x+2=x+14.',difficulty:2,errorTag:'signes'},
{id:'cl-short-2',type:'short',prompt:'Factorise 6x²+9x.',answer:'3x(2x+3)',explanation:'Le facteur commun maximal est 3x.',difficulty:3,errorTag:'factorisation'}]},
{id:'masse-poids',subject:'physique-chimie',title:'Masse et poids',why:'Cette distinction permet de comprendre les actions de la gravité et d’éviter de confondre kilogrammes et newtons.',prerequisites:['Multiplication','Unités kg et N'],simple:'La masse indique la quantité de matière. Le poids est la force avec laquelle un astre attire cette masse.',detailed:'La masse m se mesure en kilogrammes et reste la même si l’on change d’astre. Le poids P se mesure en newtons et dépend de l’intensité de pesanteur g. Ils sont liés par P=m×g.',analogy:'Une même personne garde la même masse sur la Terre et sur la Lune, mais elle y pèse moins car la gravité lunaire est plus faible.',workedSteps:['m=3 kg','g=10 N/kg','P=m×g','P=3×10','P=30 N'],commonErrors:[{error:'Donner le poids en kg.',fix:'kg = masse ; N = poids.'},{error:'Diviser par g au lieu de multiplier.',fix:'Pour calculer P à partir de m : P=m×g.'}],memoryTip:'M comme Masse → kg. P comme Poids → force → N.',summary:['m en kg','P en N','P=m×g','g dépend du lieu'],tests:[
{id:'mp-mcq',type:'mcq',prompt:'Quelle unité mesure le poids ?',options:['kg','N','m','W'],answer:'N',explanation:'Le poids est une force, donc en newtons.',difficulty:1},
{id:'mp-num',type:'numeric',prompt:'m=5 kg et g=10 N/kg. P = ?',answer:'50',explanation:'5×10=50 N.',difficulty:2},
{id:'mp-tf',type:'true_false',prompt:'La masse change lorsqu’on va sur la Lune.',options:['Vrai','Faux'],answer:'Faux',explanation:'La masse reste la même ; le poids change.',difficulty:2}]}
];
export const richLesson=(subject:string,id:string)=>richLessons.find(x=>x.subject===subject&&x.id===id);
