import {mathsRichBatch} from './maths-rich-batch';
import {frenchRichBatch} from './french-rich-batch';
import {pcRichBatch} from './pc-rich-batch';
import {svtRichBatch} from './svt-rich-batch';
import {hgRichBatch} from './hg-rich-batch';
import {englishRichBatch} from './english-rich-batch';
import {edhcRichBatch} from './edhc-rich-batch';
import {complementaryRichBatch} from './complementary-rich-batch';
export type TestItem={id:string;type:'mcq'|'true_false'|'fill'|'numeric'|'order'|'short';prompt:string;options?:string[];answer:string|string[];explanation:string;difficulty:1|2|3|4;errorTag?:string};
export type RichLesson={id:string;subject:string;title:string;why:string;prerequisites:string[];simple:string;detailed:string;analogy:string;workedSteps:string[];commonErrors:{error:string;fix:string}[];memoryTip:string;summary:string[];tests:TestItem[];remediation:{errorTag:string;message:string;action:string}[]};
const coreRichLessons:RichLesson[]=[
{id:'calcul-litteral',subject:'mathematiques',title:'Calcul littéral',why:'Le calcul littéral permet de représenter une situation avec des lettres, de simplifier des calculs et de résoudre ensuite des équations.',prerequisites:['Priorités opératoires','Nombres relatifs','Distributivité simple'],simple:'Une lettre comme x représente un nombre que l’on ne connaît pas encore ou qui peut changer. On manipule alors l’expression en respectant exactement les mêmes règles qu’avec des nombres.',detailed:'Développer transforme un produit en somme : k(a+b)=ka+kb. Réduire rassemble uniquement les termes de même nature. Factoriser fait le chemin inverse : on repère un facteur commun et on transforme une somme en produit. Ces transformations conservent la valeur de l’expression.',analogy:'Imagine des sacs identiques : 3(x+2) signifie trois sacs contenant chacun x objets et 2 objets supplémentaires. En ouvrant les trois sacs, on obtient 3x+6.',workedSteps:['Expression : 3(x+4)-2(x-1)','Distribuer 3 : 3x+12-2(x-1)','Distribuer -2 : 3x+12-2x+2','Regrouper : (3x-2x)+(12+2)','Résultat : x+14'],commonErrors:[{error:'Oublier de distribuer le signe moins.',fix:'Considère -2 comme un nombre complet : -2×x et -2×(-1).'},{error:'Additionner 3x et 12.',fix:'On ne réduit que les termes de même nature : x avec x, nombres avec nombres.'}],memoryTip:'Développer = ouvrir les parenthèses. Factoriser = reconstruire une parenthèse.',summary:['Distribuer à tous les termes','Respecter les signes','Regrouper uniquement les termes semblables','Toujours vérifier avec une valeur simple de x'],remediation:[{errorTag:'signes',message:'Le blocage vient probablement de la règle des signes.',action:'Revoir les produits de nombres relatifs avant de refaire un développement.'},{errorTag:'factorisation',message:'Tu cherches peut-être la parenthèse avant le facteur commun.',action:'Entoure d’abord ce qui divise tous les termes.'}],tests:[
{id:'cl-mcq-1',type:'mcq',prompt:'Quelle expression est égale à 2(x+5) ?',options:['2x+5','2x+10','x+10','7x'],answer:'2x+10',explanation:'2 multiplie x ET 5.',difficulty:1,errorTag:'distributivite'},
{id:'cl-fill-1',type:'fill',prompt:'Complète : 4(x-3) = 4x + ___',answer:'-12',explanation:'4×(-3)=-12.',difficulty:1,errorTag:'signes'},
{id:'cl-tf-1',type:'true_false',prompt:'3x + 5x = 8x.',options:['Vrai','Faux'],answer:'Vrai',explanation:'Ce sont deux termes de même nature.',difficulty:1},
{id:'cl-short-1',type:'short',prompt:'Développe et réduis 3(x+4)-2(x-1).',answer:'x+14',explanation:'3x+12-2x+2=x+14.',difficulty:2,errorTag:'signes'},
{id:'cl-short-2',type:'short',prompt:'Factorise 6x²+9x.',answer:'3x(2x+3)',explanation:'Le facteur commun maximal est 3x.',difficulty:3,errorTag:'factorisation'}]},
{id:'masse-poids',subject:'physique-chimie',title:'Masse et poids',why:'Cette distinction permet de comprendre les actions de la gravité et d’éviter de confondre kilogrammes et newtons.',prerequisites:['Multiplication','Unités kg et N'],simple:'La masse indique la quantité de matière. Le poids est la force avec laquelle un astre attire cette masse.',detailed:'La masse m se mesure en kilogrammes et reste la même si l’on change d’astre. Le poids P se mesure en newtons et dépend de l’intensité de pesanteur g. Ils sont liés par P=m×g.',analogy:'Une même personne garde la même masse sur la Terre et sur la Lune, mais elle y pèse moins car la gravité lunaire est plus faible.',workedSteps:['m=3 kg','g=10 N/kg','P=m×g','P=3×10','P=30 N'],commonErrors:[{error:'Donner le poids en kg.',fix:'kg = masse ; N = poids.'},{error:'Diviser par g au lieu de multiplier.',fix:'Pour calculer P à partir de m : P=m×g.'}],memoryTip:'M comme Masse → kg. P comme Poids → force → N.',summary:['m en kg','P en N','P=m×g','g dépend du lieu'],remediation:[{errorTag:'unites',message:'Tu confonds peut-être la grandeur et son unité.',action:'Associe masse→kg et poids→N avant tout calcul.'},{errorTag:'formule',message:'La relation P=m×g n’est pas encore automatisée.',action:'Écris les trois grandeurs avec unités puis remplace seulement après.'}],tests:[
{id:'mp-mcq',type:'mcq',prompt:'Quelle unité mesure le poids ?',options:['kg','N','m','W'],answer:'N',explanation:'Le poids est une force, donc en newtons.',difficulty:1},
{id:'mp-num',type:'numeric',prompt:'m=5 kg et g=10 N/kg. P = ?',answer:'50',explanation:'5×10=50 N.',difficulty:2},
{id:'mp-tf',type:'true_false',prompt:'La masse change lorsqu’on va sur la Lune.',options:['Vrai','Faux'],answer:'Faux',explanation:'La masse reste la même ; le poids change.',difficulty:2}]},
{id:'racines-carrees',subject:'mathematiques',title:'Racines carrées',why:'Les racines carrées permettent de retrouver une longueur à partir de son carré et interviennent notamment dans Pythagore.',prerequisites:['Carrés parfaits','Multiplication','Décomposition en facteurs'],simple:'√a est le nombre positif dont le carré vaut a. Par exemple √25=5 car 5²=25.',detailed:'Pour simplifier √n, on cherche dans n un facteur carré parfait. Ainsi √50=√(25×2)=5√2. On peut ensuite additionner seulement des radicaux semblables, comme on regroupe des termes en x.',analogy:'√a est comme la question inverse de « mettre au carré » : si le carré construit a une aire de 36, son côté mesure √36=6.',workedSteps:['Expression : √50 - 2√8','√50=√(25×2)=5√2','√8=√(4×2)=2√2','2√8=4√2','5√2-4√2=√2'],commonErrors:[{error:'Écrire √(a+b)=√a+√b.',fix:'Cette propriété est fausse en général. Simplifie chaque racine en factorisant son contenu.'},{error:'Additionner 5√2 et 3√3.',fix:'Les radicaux sont différents : on ne peut pas les réduire ensemble.'}],memoryTip:'Cherche d’abord le plus grand carré parfait caché sous la racine.',summary:['√a≥0','Chercher un facteur carré parfait','Regrouper seulement les mêmes radicaux','Vérifier en élevant au carré quand c’est possible'],remediation:[{errorTag:'carres',message:'Les carrés parfaits ne sont pas assez automatisés.',action:'Réviser 1² à 15² puis refaire les simplifications.'}],tests:[{id:'rc-mcq',type:'mcq',prompt:'√49 vaut ?',options:['6','7','14','24,5'],answer:'7',explanation:'7²=49.',difficulty:1,errorTag:'carres'},{id:'rc-fill',type:'fill',prompt:'√72 = ___√2',answer:'6',explanation:'72=36×2 donc √72=6√2.',difficulty:2},{id:'rc-tf',type:'true_false',prompt:'√9 + √16 = √25.',options:['Vrai','Faux'],answer:'Faux',explanation:'√9+√16=3+4=7, tandis que √25=5.',difficulty:2,errorTag:'proprietes'}]},
{id:'texte-argumentatif',subject:'francais',title:'Le texte argumentatif',why:'Argumenter permet de défendre une opinion de façon claire, logique et convaincante à l’écrit comme à l’oral.',prerequisites:['Phrase correcte','Connecteurs logiques','Différence entre fait et opinion'],simple:'Un texte argumentatif défend une idée appelée thèse à l’aide de raisons appelées arguments, souvent illustrées par des exemples.',detailed:'La thèse répond à la question « quelle position je défends ? ». Chaque argument apporte une raison distincte. L’exemple rend l’argument concret. Des connecteurs comme d’abord, ensuite, cependant, donc ou enfin rendent le raisonnement lisible.',analogy:'C’est comme plaider une cause : annoncer sa position ne suffit pas, il faut fournir des raisons et des preuves compréhensibles.',workedSteps:['Sujet : Faut-il limiter le téléphone à l’école ?','Choisir une thèse claire','Trouver deux arguments différents','Ajouter un exemple à chaque argument','Relier les idées avec des connecteurs','Conclure sans introduire un nouvel argument'],commonErrors:[{error:'Donner seulement son opinion.',fix:'Après chaque opinion, demande-toi : pourquoi ? La réponse devient un argument.'},{error:'Répéter le même argument avec d’autres mots.',fix:'Chaque paragraphe doit apporter une raison nouvelle.'}],memoryTip:'T-A-E : Thèse → Argument → Exemple.',summary:['Une thèse claire','Des arguments distincts','Des exemples pertinents','Des connecteurs logiques','Une conclusion cohérente'],remediation:[{errorTag:'argument',message:'Tu confonds peut-être opinion et argument.',action:'Pour chaque phrase, demande : est-ce ma position ou une raison qui la soutient ?'}],tests:[{id:'ta-mcq',type:'mcq',prompt:'Dans un texte argumentatif, la thèse est…',options:['un exemple','la position défendue','le titre','une répétition'],answer:'la position défendue',explanation:'La thèse est l’idée principale que l’auteur cherche à défendre.',difficulty:1},{id:'ta-order',type:'order',prompt:'Remets dans l’ordre logique.',answer:['thèse','argument','exemple','conclusion'],explanation:'On annonce la position, on la justifie, on illustre puis on conclut.',difficulty:2},{id:'ta-short',type:'short',prompt:'Donne un argument en faveur de la lecture régulière.',answer:'réponse ouverte',explanation:'La réponse doit donner une raison claire, différente d’un simple « j’aime lire ».',difficulty:3}]},
{id:'forces',subject:'physique-chimie',title:'Les forces',why:'Comprendre les forces permet d’expliquer pourquoi un objet démarre, s’arrête, change de direction ou se déforme.',prerequisites:['Vecteur : direction et sens','Unités de mesure'],simple:'Une force représente une action mécanique exercée sur un objet. Elle peut modifier son mouvement ou le déformer.',detailed:'On représente une force par un vecteur. Pour la décrire complètement, on précise son point d’application, sa direction, son sens et son intensité en newtons. Plusieurs forces peuvent agir simultanément sur un même solide.',analogy:'Quand tu tires une valise, la poignée indique où tu agis, ton bras donne la direction et le sens, et l’effort fourni correspond à l’intensité.',workedSteps:['Identifier l’objet étudié','Repérer qui agit sur lui','Nommer la force','Déterminer point d’application, direction et sens','Donner ou calculer son intensité si possible'],commonErrors:[{error:'Confondre direction et sens.',fix:'La direction est la ligne d’action (verticale, horizontale…) ; le sens indique vers où sur cette ligne.'},{error:'Oublier le point d’application.',fix:'Demande où l’action agit concrètement sur l’objet.'}],memoryTip:'PDSI : Point, Direction, Sens, Intensité.',summary:['Une force est une action mécanique','Elle se mesure en N','Elle se représente par un vecteur','PDSI décrit une force'],remediation:[{errorTag:'pdis',message:'Les caractéristiques d’une force sont mélangées.',action:'Utilise systématiquement PDSI sur trois exemples du quotidien.'}],tests:[{id:'f-mcq',type:'mcq',prompt:'Quelle unité mesure une force ?',options:['kg','N','W','m'],answer:'N',explanation:'L’unité SI de force est le newton.',difficulty:1},{id:'f-tf',type:'true_false',prompt:'Direction et sens signifient exactement la même chose.',options:['Vrai','Faux'],answer:'Faux',explanation:'La direction est une ligne ; le sens est une orientation sur cette ligne.',difficulty:1,errorTag:'pdis'},{id:'f-short',type:'short',prompt:'Cite les quatre caractéristiques d’une force.',answer:'point d’application, direction, sens, intensité',explanation:'On peut retenir PDSI.',difficulty:2,errorTag:'pdis'}]}
];
const allRich=[...coreRichLessons,...mathsRichBatch,...frenchRichBatch,...pcRichBatch,...svtRichBatch,...hgRichBatch,...englishRichBatch,...edhcRichBatch,...complementaryRichBatch];
export const richLessons:RichLesson[]=Array.from(new Map(allRich.map(l=>[l.subject+':'+l.id,l])).values());
export const richLesson=(subject:string,id:string)=>richLessons.find(x=>x.subject===subject&&x.id===id);
