export type Course={id:string;title:string;summary:string;goals:string[];sections:{title:string;body:string;key?:string;example?:string}[];check:{q:string;answer:string}};
export type Subject={id:string;name:string;icon:string;description:string;courses:Course[]};
const slug=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const C=(title:string,summary:string,body:string,key:string,example:string):Course=>({id:slug(title),title,summary,goals:['Comprendre la notion','Retenir les éléments essentiels','Savoir l’expliquer et l’appliquer'],sections:[{title:'Comprendre',body,key},{title:'Appliquer',body:'Utilise la notion dans une situation concrète. Commence par identifier ce que la question demande, sélectionne les informations utiles, puis justifie ta réponse.',example}],check:{q:`Explique « ${title} » en trois idées essentielles puis donne un exemple.`,answer:'Une bonne réponse contient l’idée centrale, une explication correcte et un exemple pertinent.'}});
const make=(items:[string,string,string,string,string][])=>items.map(x=>C(...x));
export const subjects:Subject[]=[
{id:'francais',name:'Français',icon:'FR',description:'Comprendre, argumenter et écrire avec précision.',courses:make([
['Le texte argumentatif','Défendre une idée avec des arguments organisés.','Un texte argumentatif présente une thèse et cherche à convaincre. Chaque argument doit être expliqué et peut être soutenu par un exemple. Les connecteurs logiques organisent le raisonnement.','Structure : thèse → arguments → exemples → conclusion.','Sujet : « Le téléphone est-il utile à l’école ? » Choisis une position, donne deux arguments et illustre-les.'],
['Le résumé du texte argumentatif','Restituer fidèlement l’essentiel d’un texte.','Résumer consiste à conserver les idées principales et leur ordre logique en supprimant exemples secondaires, répétitions et détails. On reformule sans commenter.','Fidélité, concision, reformulation, cohérence.','Lis un paragraphe argumentatif, repère sa thèse et ses deux arguments puis reformule-les en trois phrases.'],
['La communication','Identifier les éléments d’une situation de communication.','Toute communication met en relation un émetteur et un récepteur autour d’un message transmis par un canal, dans un contexte et avec un code partagé.','Émetteur · récepteur · message · canal · code · contexte.','Dans une annonce radio, identifie qui parle, à qui, par quel canal et dans quel but.'],
['La pronominalisation','Éviter les répétitions grâce aux pronoms.','La pronominalisation remplace un groupe nominal par un pronom adapté à sa fonction et à son sens. Il faut vérifier genre, nombre et place du pronom.','Ex. : Je vois Awa → Je la vois.','Remplace « les cahiers » dans : Je range les cahiers.'],
['Orthographe grammaticale','Accorder correctement les mots dans la phrase.','L’orthographe grammaticale concerne notamment les accords dans le groupe nominal et l’accord du verbe avec son sujet. Identifier le donneur d’accord évite beaucoup d’erreurs.','Sujet ↔ verbe ; nom ↔ déterminant/adjectif.','Corrige : « Les élève sérieux travaille. » puis justifie chaque accord.']
])},
{id:'physique-chimie',name:'Physique-Chimie',icon:'PC',description:'Observer, modéliser et calculer.',courses:make([
['Masse et poids d’un corps','Distinguer masse et poids.','La masse mesure la quantité de matière et s’exprime en kilogrammes. Le poids est une force due à l’attraction de la Terre et s’exprime en newtons. Ils sont liés par P = m×g.','P = m × g ; masse en kg, poids en N.','Pour m=3 kg et g=10 N/kg, P=30 N.'],
['Les forces','Décrire une action mécanique.','Une force se représente par un vecteur caractérisé par son point d’application, sa direction, son sens et son intensité. Une force peut modifier le mouvement ou déformer un objet.','4 caractéristiques : point, direction, sens, intensité.','Décris la force exercée par une corde qui tire un chariot.'],
['Travail et puissance mécaniques','Relier force, déplacement et durée.','Lorsqu’une force provoque un déplacement, elle peut effectuer un travail. La puissance mesure la rapidité avec laquelle un travail est effectué.','Puissance = travail / durée.','Deux machines font le même travail ; celle qui le fait en moins de temps est la plus puissante.'],
['Puissance et énergie électriques','Calculer une consommation électrique.','La puissance d’un appareil indique le rythme auquel il utilise l’énergie. Pour une puissance constante, l’énergie consommée est le produit de la puissance par la durée.','E = P × t ; kWh = kW × h.','Un appareil de 1 kW pendant 3 h consomme 3 kWh.'],
['Solutions acides, basiques et neutres','Interpréter le pH.','Le pH permet de caractériser une solution : inférieur à 7 elle est acide, égal à 7 elle est neutre, supérieur à 7 elle est basique.','pH<7 acide ; pH=7 neutre ; pH>7 basique.','Classe des solutions de pH 2, 7 et 11.']
])},
{id:'svt',name:'SVT',icon:'SVT',description:'Comprendre le corps humain et son environnement.',courses:make([
['Les aliments et l’Homme','Relier alimentation et besoins de l’organisme.','Les aliments apportent des nutriments nécessaires à l’énergie, à la construction et au fonctionnement du corps. Une alimentation équilibrée varie les groupes d’aliments et adapte les quantités aux besoins.','Besoins : énergie · construction · fonctionnement.','Compose un repas équilibré et explique le rôle de chaque groupe choisi.'],
['La digestion des aliments','Comprendre la transformation des aliments.','La digestion associe transformations mécaniques et chimiques. Elle produit des nutriments suffisamment simples pour traverser la paroi intestinale et rejoindre le milieu intérieur.','Aliments → digestion → nutriments → absorption.','Explique pourquoi mâcher facilite la digestion.'],
['Le sang','Identifier les constituants et leurs rôles.','Le sang comprend plasma, globules rouges, globules blancs et plaquettes. Les globules rouges transportent surtout le dioxygène ; les globules blancs participent à la défense ; les plaquettes à la coagulation.','GR : O₂ · GB : défense · plaquettes : coagulation.','Associe chaque constituant à son rôle principal.'],
['La circulation sanguine','Suivre le trajet du sang.','Le cœur propulse le sang dans un réseau de vaisseaux. Les artères conduisent le sang depuis le cœur, les veines le ramènent et les capillaires permettent les échanges avec les tissus.','Cœur → artères → capillaires → veines → cœur.','Explique le rôle des capillaires.'],
['La protection et l’amélioration des sols','Préserver la fertilité des sols.','L’érosion, le déboisement et certaines pratiques agricoles dégradent les sols. Couverture végétale, rotation des cultures, apport raisonné de matière organique et lutte contre l’érosion contribuent à leur protection.','Protéger le sol = limiter érosion + maintenir fertilité.','Propose deux actions pour protéger un sol en pente.']
])},
{id:'histoire-geographie',name:'Histoire-Géographie',icon:'HG',description:'Construire des repères et analyser les territoires.',courses:make([
['L’accession de la Côte d’Ivoire à l’indépendance','Comprendre le processus menant à 1960.','L’indépendance ivoirienne s’inscrit dans la décolonisation de l’après-guerre. L’évolution politique, les revendications africaines et les transformations de l’empire colonial français conduisent à la souveraineté proclamée le 7 août 1960.','Repère : 7 août 1960.','Construis une courte frise situant l’indépendance dans le contexte de la décolonisation.'],
['La Deuxième Guerre mondiale','Identifier causes, caractères et conséquences.','Le conflit de 1939-1945 devient mondial, mobilise sociétés et économies et se caractérise par une violence extrême contre militaires et civils. Il bouleverse les rapports de puissance et favorise la création de l’ONU.','1939-1945 · guerre mondiale · conséquences humaines et politiques.','Classe trois conséquences en catégories : humaine, économique, politique.'],
['L’Organisation des Nations Unies (ONU)','Comprendre le rôle de l’ONU.','Créée en 1945, l’ONU vise notamment le maintien de la paix et de la sécurité internationales, la coopération entre États et la promotion des droits humains.','1945 · paix · coopération · droits humains.','Donne deux missions de l’ONU et un exemple d’action possible.'],
['Les secteurs d’activités économiques de la Côte d’Ivoire','Distinguer primaire, secondaire et tertiaire.','Le secteur primaire exploite les ressources naturelles, le secondaire transforme les matières premières et le tertiaire regroupe les services. Leur articulation structure l’économie ivoirienne.','Primaire → production ; secondaire → transformation ; tertiaire → services.','Classe cacao, usine de chocolat et banque dans les trois secteurs.'],
['La place de l’Afrique dans la mondialisation','Analyser insertion, atouts et défis.','L’Afrique participe aux échanges mondiaux par ses ressources, ses marchés, ses services, ses diasporas et ses innovations. Son insertion reste marquée par des dépendances, des inégalités et un besoin de transformation locale accrue.','Flux · échanges · transformation locale · intégration.','Explique pourquoi transformer localement une matière première peut créer davantage de valeur.']
])},
{id:'anglais',name:'Anglais',icon:'EN',description:'Read, use English and write clearly.',courses:make([
['Life at school','Talk about school experiences.','Use school vocabulary and the simple past to describe completed experiences. Reading questions often require finding explicit information and inferring a simple meaning from context.','Simple past: regular -ed / common irregular verbs.','Write five sentences about your last school week.'],
['Women at work','Discuss work and equal opportunities.','This unit develops vocabulary about occupations, responsibilities and rights. Use modal verbs and expressions of opinion to discuss opportunities for women and girls.','Opinion: I think… / In my view… ; ability: can.','Give two reasons why girls’ education matters.'],
['Travelling','Communicate during a journey.','Learn transport, airport and tourism vocabulary. Practice asking for information, understanding signs and describing travel plans.','Where…? How much…? What time…?','Write a short dialogue asking for departure time and destination.'],
['Human rights','Express rights, duties and tolerance.','Distinguish a right from a duty and use modal verbs to express obligation, permission and advice.','must / mustn’t / should / can.','Write three classroom duties using must or should.'],
['Hygiene and health','Give health and hygiene advice.','Use health vocabulary and structures for advice and prevention. Connect causes, consequences and preventive behaviours.','You should… / You must… / Avoid…','Give four pieces of advice for good hygiene at school.']
])},
{id:'edhc',name:'EDHC',icon:'EDHC',description:'Agir en citoyen responsable.',courses:make([
['Le vote et la participation citoyenne','Comprendre la participation à la vie publique.','Le vote permet aux citoyens remplissant les conditions légales de participer au choix de représentants ou à certaines décisions. La citoyenneté comprend aussi information, respect des règles et engagement responsable.','Participation = droits + devoirs + responsabilité.','Cite deux comportements responsables pendant une période électorale.'],
['L’impôt et le développement','Relier contribution collective et services publics.','L’impôt est une contribution prévue par la loi qui participe au financement des services et investissements publics. Son utilisation concerne notamment infrastructures, éducation, santé et fonctionnement des institutions.','Impôt → ressources publiques → services/investissements.','Donne trois services publics pouvant être financés par les recettes publiques.'],
['L’utilisation rationnelle des biens publics','Préserver les ressources de la collectivité.','Un bien public est destiné à l’usage ou au service de la collectivité. Le dégrader impose un coût à tous ; le préserver participe au bien-être commun.','Bien public = responsabilité collective.','Que faire si tu constates une dégradation volontaire d’un équipement scolaire ?'],
['Le projet d’entreprise','Comprendre les bases d’un projet économique.','Un projet d’entreprise part d’un besoin ou problème, propose une solution, identifie des bénéficiaires ou clients et prévoit les ressources nécessaires à sa réalisation.','Besoin → solution → bénéficiaires → ressources.','Imagine un petit service utile autour de ton école et précise à quel besoin il répond.'],
['Gestion rationnelle de l’eau','Relier ressource, comportements et paix sociale.','L’eau est une ressource essentielle. Éviter gaspillage et pollution, entretenir les installations et organiser équitablement l’accès contribuent à sa disponibilité et réduisent les tensions.','Économiser · protéger · partager équitablement.','Propose trois gestes pour réduire le gaspillage d’eau à la maison ou à l’école.']
])}
];
export const subjectById=(id:string)=>subjects.find(s=>s.id===id);export const courseById=(sid:string,cid:string)=>subjectById(sid)?.courses.find(c=>c.id===cid);
