export type SubjectLesson={id:string;title:string;summary:string;points:string[]};
export type Subject={id:string;name:string;description:string;lessons:SubjectLesson[]};
const slug=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const make=(titles:string[],summary:string):SubjectLesson[]=>titles.map(t=>({id:slug(t),title:t,summary,points:['Comprendre les notions essentielles','Savoir les expliquer avec ses propres mots','S’entraîner sur une situation simple']}));
export const subjects:Subject[]=[
{id:'francais',name:'Français',description:'Lecture, expression, grammaire et orthographe.',lessons:make(['Le dialogue oral','L’exposé oral','Le débat','Œuvre intégrale','Le texte argumentatif','L’article de journal','Le résumé du texte argumentatif','La communication','La pronominalisation','L’adverbe et le groupe adverbial','L’infinitif et le participe','La coordination','L’expression des circonstances','Orthographe lexicale','Orthographe grammaticale'],'Développer les compétences de compréhension et d’expression attendues en 3e.')},
{id:'physique-chimie',name:'Physique-Chimie',description:'Mécanique, optique, électricité et chimie.',lessons:make(['Masse et poids d’un corps','Les forces','Équilibre d’un solide soumis à deux forces','Travail et puissance mécaniques','Énergie mécanique','Électrolyse et synthèse de l’eau','Les alcanes','Les lentilles','Les défauts de l’œil et leurs corrections','Oxydation des corps purs simples','Réduction des oxydes','Solutions acides, basiques et neutres','Puissance et énergie électriques','Le conducteur ohmique'],'Comprendre un phénomène, utiliser les relations utiles et résoudre des situations scientifiques.')},
{id:'svt',name:'SVT',description:'Nutrition, santé, reproduction et sols.',lessons:make(['Les aliments et l’Homme','La digestion des aliments','Le sang','La transfusion sanguine','La circulation sanguine','Les grossesses précoces et les moyens de prévention','L’infection au VIH','Les caractéristiques d’un sol','Les relations sols-plantes','La dégradation des sols','La protection et l’amélioration des sols'],'Observer, expliquer des mécanismes biologiques et environnementaux et exploiter des documents.')},
{id:'histoire-geographie',name:'Histoire-Géographie',description:'Côte d’Ivoire, Afrique, monde et mondialisation.',lessons:make(['Le mouvement impérialiste et la colonisation en Côte d’Ivoire','L’accession de la Côte d’Ivoire à l’indépendance','Causes et caractères des crises sociopolitiques de l’Afrique indépendante','La crise rwandaise : de la guerre au génocide des Tutsi (1990-1994)','Les causes, les caractères et les conséquences de la Deuxième Guerre mondiale','L’Organisation des Nations Unies (ONU)','L’Union Africaine (UA)','Les atouts du développement économique de la Côte d’Ivoire','Les secteurs d’activités économiques de la Côte d’Ivoire','Les problèmes du développement économique de la Côte d’Ivoire','Étude économique de l’Afrique','La place de l’Afrique dans la mondialisation'],'Construire des repères, expliquer des faits et exploiter des documents historiques ou géographiques.')},
{id:'anglais',name:'Anglais',description:'Reading, Language in Use et Writing.',lessons:make(['Life at school','Women at work','Travelling','Fashion','City or village?','Human rights','Hygiene and health','Information and Communication Technologies'],'Comprendre et produire un anglais simple autour des thèmes officiels de 3e.')},
{id:'edhc',name:'EDHC',description:'Citoyenneté, droits, santé, société et environnement.',lessons:make(['Les devoirs des parents','Les organisations humanitaires','La protection des personnes vulnérables','Partis politiques, institutions et paix sociale','Le vote et la participation citoyenne','L’impôt et le développement','L’utilisation rationnelle des biens publics','Le projet d’entreprise','Les alliances interethniques','Centres de santé et lutte contre l’automédication','Dépistage du VIH','Protection des parcs et réserves','Gestion rationnelle de l’eau'],'Relier connaissances civiques, comportements responsables et situations de la vie courante.')}
];
export const subjectById=(id:string)=>subjects.find(s=>s.id===id);export const subjectLesson=(sid:string,lid:string)=>subjectById(sid)?.lessons.find(l=>l.id===lid);
